name: Update Dependency

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  main:
    name: update dependency
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: 2.x
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git switch -C update-dependency
      - run: deno outdated --update --latest
      - run: |
          if git diff --quiet main..update-dependency; then
            echo "rn=false" >> $GITHUB_OUTPUT
          else
            echo "rn=true" >> $GITHUB_OUTPUT
          fi
        id: check_update
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          commit-message: "build: bump version deno imports"
          branch: update-deno-imports
          delete-branch: true
          title: "build: bump version deno imports"
